#!/bin/bash

# Playwright Test Runner with Email Report
# Usage: ./run-tests-with-report.sh [email@example.com]

# Configuration
TIMESTAMP=$(date +"%Y-%m-%d_%H-%M-%S")
REPORT_DIR="test-reports/$TIMESTAMP"
EMAIL_TO="${1:-your-email@example.com}"
WORKERS=2

echo "🚀 Starting Playwright Test Suite..."
echo "📅 Timestamp: $TIMESTAMP"
echo "📧 Report will be sent to: $EMAIL_TO"
echo ""

# Create report directory
mkdir -p "$REPORT_DIR"

# Run tests with multiple reporters
echo "▶️  Running tests with $WORKERS workers..."
npx playwright test \
  --reporter=html,json,list \
  --workers=$WORKERS \
  --output="$REPORT_DIR" \
  > "$REPORT_DIR/test-output.log" 2>&1

TEST_EXIT_CODE=$?

# Copy reports to the report directory
if [ -f "playwright-report/index.html" ]; then
    cp -r playwright-report/* "$REPORT_DIR/"
fi

if [ -f "test-results.json" ]; then
    cp test-results.json "$REPORT_DIR/"
fi

# Generate summary
echo ""
echo "📊 Generating test summary..."
node scripts/generate-summary.js > "$REPORT_DIR/summary.md"

# Display summary in terminal
echo ""
echo "=============================================="
cat "$REPORT_DIR/summary.md"
echo "=============================================="
echo ""

# Generate HTML email report
cat > "$REPORT_DIR/email-report.html" << EOF
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <style>
        body { font-family: Arial, sans-serif; line-height: 1.6; color: #333; max-width: 800px; margin: 0 auto; padding: 20px; }
        h1 { color: #2c3e50; border-bottom: 3px solid #3498db; padding-bottom: 10px; }
        h2 { color: #2980b9; margin-top: 30px; }
        table { border-collapse: collapse; width: 100%; margin: 20px 0; }
        th, td { border: 1px solid #ddd; padding: 12px; text-align: left; }
        th { background-color: #3498db; color: white; }
        tr:nth-child(even) { background-color: #f2f2f2; }
        .passed { color: #27ae60; font-weight: bold; }
        .failed { color: #e74c3c; font-weight: bold; }
        .stats { background-color: #ecf0f1; padding: 15px; border-radius: 5px; margin: 20px 0; }
        .footer { margin-top: 40px; padding-top: 20px; border-top: 1px solid #ddd; color: #7f8c8d; font-size: 0.9em; }
    </style>
</head>
<body>
    <h1>🧪 Playwright Test Report</h1>
    <div class="stats">
        <p><strong>Timestamp:</strong> $TIMESTAMP</p>
        <p><strong>Environment:</strong> $(hostname)</p>
        <p><strong>Branch:</strong> $(git branch --show-current 2>/dev/null || echo "N/A")</p>
    </div>
    
    <h2>📊 Test Results</h2>
    <pre>$(cat "$REPORT_DIR/summary.md")</pre>
    
    <p>📎 <strong>Full HTML Report:</strong> See attached file or check <code>$REPORT_DIR</code></p>
    
    <div class="footer">
        <p>Generated by Playwright Test Runner</p>
        <p>Report Location: $REPORT_DIR</p>
    </div>
</body>
</html>
EOF

# Print report location
echo "📁 Reports saved to: $REPORT_DIR"
echo "   - HTML Report: $REPORT_DIR/index.html"
echo "   - JSON Report: $REPORT_DIR/test-results.json"
echo "   - Summary: $REPORT_DIR/summary.md"
echo ""

# Open HTML report in browser (optional)
if command -v open &> /dev/null; then
    echo "🌐 Opening HTML report in browser..."
    open "$REPORT_DIR/index.html"
fi

# Send email using mail command (if available)
if command -v mail &> /dev/null; then
    echo "📧 Sending email report to $EMAIL_TO..."
    cat "$REPORT_DIR/email-report.html" | mail -s "Playwright Test Report - $TIMESTAMP" "$EMAIL_TO"
    echo "✅ Email sent!"
else
    echo "⚠️  'mail' command not available. Email not sent."
    echo "   Install mailutils: sudo apt-get install mailutils (Linux)"
    echo "   Or use the sendmail script below"
fi

# Exit with the same code as the tests
exit $TEST_EXIT_CODE
